#!/bin/bash

################################################################################
#	License
################################################################################
#
#	Copyright (c) 2011 Brandon Pierce <brandon@ihashacks.com>
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

################################################################################
#	Changelog
################################################################################
#
#   Written 20110620 Brandon Pierce <brandon@ihashacks.com>
#
#   	Verifies that a web server can authentication NTLM
#

################################################################################
#	Documentation
################################################################################
#
# Sample Nagios command.cfg definition
# 
#   # 'check_http_ntlm' command definition
#   define command {
#       command_name    check_http_ntlm
#       command_line    $USER1$/check_http_ntlm $ARG1$ $USER3$
#   }
#
# Sample Nagios host entry
#
#   define service {
#       host_name               Server
#       service_description     NTLM Authenticated Web Site
#       is_volatile             0
#       check_period            24x7
#       max_check_attempts      3
#       normal_check_interval   5
#       retry_check_interval    1
#       contact_groups          nagiosadmins
#       notification_interval   120
#       notification_period     24x7
#       notification_options    c,r
#       check_command           check_http_ntlm!https://server.com
#   }
#

PROG=/usr/bin/curl
HOST=$1
AUTH=$2

$PROG -s -S --ntlm --head -u $AUTH -k $HOST | grep -w 200 > /dev/null

if [ $? -eq 0 ]
  then
    echo "Authentication Success"
     else echo "Authentication Failure"
  exit 2
fi
