#!/bin/bash

################################################################################
#	License
################################################################################
#
#	Copyright (c) 2008, 2011, 2012 Brandon Pierce <brandon@ihashacks.com>
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

################################################################################
#	Changelog
################################################################################
#
#	Written 20081222 by Brandon Pierce <brandon@ihashacks.com>
#
#       Checks the remainder of a Dell warranty using a service tag
#
#	Updated 20110318
#
#		Picks longest lasting warranty date when multiple warranty or 
#		warranty types are listed
#
#	Updated 20110830
#
#		Included a link to the warranty site in the status output. Must have
#		escape_html_tags=0 set in your cgi.cfg
#
#		Added timeout options to lynx to hopefully resolve false positive
#		when the Dell site is slow to respond.
#
#	Updated 20120603
#
#		Overhaul this damn thing to work with Dell's re-done support site.
#		Added exit case when invalid service tag is input or some other
#		failure occurs.
#

GET="lynx -connect_timeout=30 -read_timeout=30 -dump -nocolor -nolist"
DURL="http://support.dell.com/support/topics/global.aspx/support/my_systems_info/details?c=us&l=en&s=gen&servicetag="

# help
usage()
{
	echo "Usage: `basename $0` -s <service tag> -w <warning days> -c <critical days>"
	exit 3
}

# parse parameters and options
while getopts ":s:w:c:" OPT; do
	case "$OPT" in
		s)
			SVCTAG=$OPTARG
			;;
		w)
			DWARN=$OPTARG
			;;
		c)
			DCRIT=$OPTARG
			;;
		\?)
			usage
			;;
		:)
			usage
			;;
	esac
done

# retrieve the Dell warranty with most remaining days
DAYSLEFT=`$GET "$DURL$SVCTAG" | \
	grep -m 1 -o '\[[0-9]*\]' |\
	sed -e 's/\[// ; s/\]//'`

# test it
if [ ! -n "$DAYSLEFT" ]; then
	echo "Unable to verify the Service Tag"
	exit 3
elif [ $DAYSLEFT -le "0" ]; then
	echo "Warranty has expired for <a href=$DURL$SVCTAG>$SVCTAG</a>"
	exit 2
elif [ $DAYSLEFT -le $DCRIT ]; then
	echo "Warranty expires in $DAYSLEFT days for <a href=$DURL$SVCTAG>$SVCTAG</a>"
	exit 2
elif [ $DAYSLEFT -le $DWARN ]; then
	echo "Warranty expires in $DAYSLEFT days for <a href=$DURL$SVCTAG>$SVCTAG</a>"
	exit 1
else
	echo "Warranty expires in $DAYSLEFT days for <a href=$DURL$SVCTAG>$SVCTAG</a>"
	exit 0
fi
